IDC_BUTTON_TEMPLATE_IMPORT 



 SelectTreeItem 


 ID_ADD_BASE_CONDENSATE_NODE 
 
 
 
 SELECT  DISTINCT COMPANYNAME FROM TMP_DEP_HEADER  
 SELECT DISTINCT ENTITY FROM TMP_DEP_HEADER  WHERE COMPANYNAME = 'ADDAX加蓬公司'
 SELECT DISTINCT BLOCK FROM TMP_DEP_HEADER  WHERE ENTITY = 'ADDAX原加蓬' AND COMPANYNAME = 'ADDAX加蓬公司'
 SELECT DISTINCT PROJECTCODE FROM TMP_DEP_HEADER WHERE BLOCK = 'Awoun' AND ENTITY = 'ADDAX原加蓬' AND COMPANYNAME = 'ADDAX加蓬公司
 
 
 
 
 
 
 